version: '3.9'

services:
  db_host:
    container_name: database
    image: postgres:16-alpine3.18
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: "12345678"
    restart: always
    ports:
      - 5433:5433
    networks:
      - botnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  tg_bot:
    container_name: sarafanka_bot
    build:
      context: .
    command: python main.py
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/sarafanka
    depends_on:
      - db_host

volumes:
  pgdata:

networks:
  botnet:
    driver:
      bridge
